default: &default
  adapter: postgresql
  encoding: utf-8
  reconnect: false
  pool: 5
  timeout: 5000
  host: db
  username: postgres

development:
  <<: *default
  database: docker-rails-demo_development
test:
  <<: *default
  database: docker-rails-demo_test

production:
  adapter: postgresql
  database: docker-rails-demo_production
  pool: 5
  timeout: 5000
